In [2]:
# import libs
import tensorflow as tf
import numpy as np

In [3]:
# create 2D tensor (3x2) with custom values
x = tf.constant([1,2,3,4,5,6], shape = [3,2], dtype=tf.float32)

In [20]:
x

<tf.Tensor: id=5, shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [4]:
# create 2D tensor (2x2) with only unit values
ones = tf.ones(shape=[2,2], dtype=tf.float32)

In [13]:
# row-wise mean
tf.math.reduce_mean(x, axis = 1)

<tf.Tensor: id=22, shape=(3,), dtype=float32, numpy=array([1.5, 3.5, 5.5], dtype=float32)>

In [14]:
# column-wise mean
tf.math.reduce_mean(x, axis = 0)

<tf.Tensor: id=24, shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

Object x is also numpy-compatible

In [17]:
# row-wise mean
np.mean(x, axis = 1)

array([1.5, 3.5, 5.5], dtype=float32)

In [18]:
# column-wise mean
np.mean(x, axis = 0)

array([3., 4.], dtype=float32)

In [21]:
# general matrix mean
np.mean(x)

3.5

In [4]:
params = tf.constant([[0, 1.0, 2.0],
                      [10.0, 11.0, 12.0],
                      [20.0, 21.0, 22.0],
                      [30.0, 31.0, 32.0]])

In [14]:
tf.gather(params, indices=[2,0], axis = 1).numpy()

array([[ 2.,  0.],
       [12., 10.],
       [22., 20.],
       [32., 30.]], dtype=float32)

In [5]:
#Q1: Create a 3-dimensional tensor with values 1,...,12 and shape (2,3,2)
x = tf.constant([i+1 for i in range(12)], shape=(2,3,2), dtype = tf.float32)

In [11]:
x

<tf.Tensor: id=3, shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]], dtype=float32)>

In [8]:
#Q2: Calculate the logarithm of this tensor
log_x = tf.math.log(x)

In [9]:
log_x

<tf.Tensor: id=4, shape=(2, 3, 2), dtype=float32, numpy=
array([[[0.       , 0.6931472],
        [1.0986123, 1.3862944],
        [1.609438 , 1.7917595]],

       [[1.9459102, 2.0794415],
        [2.1972246, 2.3025851],
        [2.3978953, 2.4849067]]], dtype=float32)>

In [12]:
#Q2: Calculate the mean along the third axis
mean_x_ax3 = tf.math.reduce_mean(x, axis = 2)

In [13]:
mean_x_ax3

<tf.Tensor: id=7, shape=(2, 3), dtype=float32, numpy=
array([[ 1.5,  3.5,  5.5],
       [ 7.5,  9.5, 11.5]], dtype=float32)>