# 1. Getting started

**TensorFlow** is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.

**Keras** is a high-level neural networks library that is running on the top of TensorFlow. Using Keras in deep learning allows for easy and fast prototyping as well as running seamlessly on CPU and GPU. This framework is written in Python code which is easy to debug and allows ease for extensibility.

In a big data world with structured and unstructured data, our input can be:
* a single time series: 1-dimensional, with 1 axis
* one sound fragment: 2-dimensional, with 2 axes
* one image in color: 3-dimensional, with 3 axes
* one movie: 4-dimensional, with 4 axes

We require a framework that can flexibly adjust to all these data structures!

TensorFlow is this flexible framework which consists of highly optimized functions based on tensors. What is a tensor?
* **1-dimensional tensor** is a vector (e.g. closing daily stock price during 250 days)
<img src="./imgs/tensor1.png" alt="tensor1" style="width: 300px;"/>
* **2-dimensional tensor** is a matrix (e.g. a tabular data set with observations and features)
<img src="./imgs/tensor2.png" alt="tensor2" style="width: 300px;"/>

* **3-dimensional tensor**, e.g. stock price dataset where one year of data can then be stored in a 3D tensor **(samples, timesteps, features)**, here **(250, 390, 3)**
    * each minute we record the current price, lowest price and highest price
    * a trading day has 390 minutes and a trading year has 250 days.
<figure>
<img src="./imgs/tensor3.png" alt="tensor3" style="width: 400px;"/>
<figcaption><center>Source: <a href="https://github.com/rstudio-conf-2020/dl-keras-tf">Bradley Boehmke</a>.<p></p></center></figcaption>
</figure>

* **4-dimensional tensor**, e.g. picture an image data set where
    * each image has a specific height and width
    * three color channels (Red, Green, Blue) are registered
    * a collection of images are stored in the structure **(samples, height, width, channels)**
<figure>
<img src="./imgs/tensor4.png" alt="tensor4" style="width: 400px;"/>
<figcaption><center>Source: <a href="https://github.com/rstudio-conf-2020/dl-keras-tf">Bradley Boehmke</a>.<p></p></center></figcaption>
</figure>

* **5-dimensional tensor**, e.g. Let's picture an video data set where
    * each video sample is one minute long and has anumber of frames per second (e.g. 4 frames persecond)
    * each frame has a specific height (e.g. 256 pixels) andwidth (e.g. 144 pixels)
    * three color channels (Red, Green, Blue)
    * multiple images ( samples ) are stored.
    * a collection of images can be stored in a 4D tensor(samples, frames, height, width, channels) whichbecomes here (samples, 240, 256, 144, 3) .
<figure>
<img src="./imgs/tensor5.png" alt="tensor5" style="width: 400px;"/>
<figcaption><center>Source: <a href="https://github.com/rstudio-conf-2020/dl-keras-tf">Bradley Boehmke</a>.<p></p></center></figcaption>
</figure>

In [33]:
# import libs
import tensorflow as tf
import numpy as np

In [34]:
# create 2D tensor (3x2) with custom values
x = tf.constant([1,2,3,4,5,6], shape = [3,2], dtype=tf.float32); x

<tf.Tensor: id=25, shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)>

In [35]:
# create 2D tensor (2x2) with only unit values
ones = tf.ones(shape=[2,2], dtype=tf.float32); ones

<tf.Tensor: id=28, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [36]:
# column-wise mean
tf.math.reduce_mean(x, axis = 0)

<tf.Tensor: id=30, shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [37]:
# row-wise mean
tf.math.reduce_mean(x, axis = 1)

<tf.Tensor: id=32, shape=(3,), dtype=float32, numpy=array([1.5, 3.5, 5.5], dtype=float32)>

**Note that** Object x is also numpy-compatible, so it is possible to calculate the mean using _np.mean_. _tf.reduce_mean_ is multi-threaded, typically calculated on your GPU. _np.mean_ is calculated on a single CPU.

In [38]:
# row-wise mean
np.mean(x, axis = 1)

array([1.5, 3.5, 5.5], dtype=float32)

In [39]:
# column-wise mean
np.mean(x, axis = 0)

array([3., 4.], dtype=float32)

In [40]:
# general matrix mean
np.mean(x)

3.5

**Question 1:** Create a 3-dimensional tensor with values 1,...,12 and shape (2,3,2)

In [41]:
x = tf.constant([i+1 for i in range(12)], shape=(2,3,2), dtype = tf.float32); x

<tf.Tensor: id=35, shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]],

       [[ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]], dtype=float32)>

**Question 2:** Calculate the logarithm

In [42]:
log_x = tf.math.log(x); log_x

<tf.Tensor: id=36, shape=(2, 3, 2), dtype=float32, numpy=
array([[[0.       , 0.6931472],
        [1.0986123, 1.3862944],
        [1.609438 , 1.7917595]],

       [[1.9459102, 2.0794415],
        [2.1972246, 2.3025851],
        [2.3978953, 2.4849067]]], dtype=float32)>

**Question 3:** Calculate the logarithm

In [43]:
mean_x_ax3 = tf.math.reduce_mean(x, axis = 2); mean_x_ax3

<tf.Tensor: id=38, shape=(2, 3), dtype=float32, numpy=
array([[ 1.5,  3.5,  5.5],
       [ 7.5,  9.5, 11.5]], dtype=float32)>